### ISSUE TITLE
Incorrect pin highlighted

### ISSUE THREAD

**Issue by MrAureliusR** [jeffmakes/pi-data-recovery#1]
According to the pinout on the datasheet you included, VCC on the eMMC is C6; however on the accompanying image, it looks like the red dot is on C5 (which is an unconnected pin). 
Just wanted to report this in case it's incorrect!
![image](https://user-images.githubusercontent.com/41264289/185770250-b5fbef9a-6c82-423c-8b21-c981c3982e93.png)

**Comment by jeffmakes** [comment]
Well spotted and thanks very much, @MrAureliusR - I've fixed it.

**Comment by jeffmakes** [comment]
Thanks, fixed it
